### PR TITLE
Show challenge completed text after challenge completion

### LINKED ISSUE #15: Show challenge completed message for users who have completed the frogtoberfest challenge
**Current behavior:**
When a user completes the requirements for frogtoberfest, the profile page still says `Only # days left! You can do it!`.

**Expected behavior:**
After completing the requirements, the profile should show `Challenge Completed` or similar message. Something like `Thank you for your contributions! You have successfully completed Frogtoberfest 2019.`

If a user has `10/10` **PRs** and `4/4` **Other PRs** (_or more_), the profile page should show a challenge completed message instead of the days remaining message above the user name input field. This message should only be displayed if both the **PR** and **Other PR** have been completed. If either one is not completed, the profile should still show the days remaining message.

Screenshot from `Hacktoberfest` which shows how the profile looks for users who have completed the hacktoberfest challenge.

image

Need not be so fancy, but an acknowledgement that the challenge is complete is needed.

**Steps to reproduce:**
- Complete the frogtoberfest challenge
- View user profile

**Image for reference:**
Screen Shot 2019-10-22 at 14 06 37

### PR DESCRIPTION
**Pull request by bhattaraib58**
Resolves #15 

## Issue
Current behavior:
When a user completes the requirements for frogtoberfest, the profile page says Only # days left! You can do it!.

## Usage Changes
Created new component for viewing of completed messages, fixed the style for new component message and aligned the other PR, Total PR, Message and Profile Pic.

After completing the requirements, the profile message. Something like Off to a great start, keep going!, Now you're just showing off!.

After completing the requirements, the profile should show Challenge Completed.

If a user has 10/10 PRs and 4/4 Other PRs (or more), the profile page shows a challenge completed message instead of the days remaining message above the user name input field. This message is displayed if both the PR and Other PR have been completed. If either one is not completed, the profile still shows the days remaining message.

Before:
Screenshot from 2019-10-23 02-41-54

After:

Screenshot from 2019-10-25 12-20-08

Screenshot from 2019-10-25 12-19-53

### CODE REVIEW

File: src/constant/frogtoberfestIgnoreLabels.js [hunk 1]
```diff
@@ -0,0 +1,2 @@
+// Ignore list of labels for frogtoberfest, add at end of array for more list
+export const FROGTOBERFEST_IGNORE_LABEL_LIST = ['invalid'];
```
Comment (mesaugat) [inline src/constant/frogtoberfestIgnoreLabels.js]: Can we use this where it's needed? It's better not to extract it away to a different file right away. Also, I see it only used once.

File: src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js [hunk 2]
```diff
@@ -0,0 +1,44 @@
+import { pullRequestAmount, otherReposAmount } from '../../pullRequestAmount';
+
+const messages = [
+  "It's not too late to start!",
+  'Off to a great start, keep going!',
+  'Off to a great start, keep going!',
```
Comment (mesaugat) [inline src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js]: Duplicate messages? Why so?

File: src/utils/isPRLabelValid.js [hunk 3]
```diff
@@ -0,0 +1,18 @@
+import { FROGTOBERFEST_IGNORE_LABEL_LIST } from '../constant/frogtoberfestIgnoreLabels';
```
Comment (mesaugat) [inline src/utils/isPRLabelValid.js]: Use the `const` directly here.

File: src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js (hunk 2 above)
Comment (bhattaraib58) [reply src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js]: Because on frogtoberfest we have to get 10 Total PR for the challenge completion criteria, so due to limited no of things to be said back to user, i have used some messages again for motivation.

File: src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js [hunk 4]
```diff
@@ -0,0 +1,44 @@
...
+];
+
+/**
+ * Get Messages Based on Pull Request and Other Repo count.
+ *
+ * @param {*} pullRequestCount
+ * @param {*} otherReposCount
+ * @returns
+ */
+const getMessage = (pullRequestCount, otherReposCount) => {
```
Comment (kabirbaidhya) [inline src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js]: Use function keyword for declaring functions.

File: src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js [hunk 5]
```diff
@@ -0,0 +1,44 @@
...
+  'Way to go!',
+  "Now you're just showing off!"
+];
+
+/**
+ * Get Messages Based on Pull Request and Other Repo count.
+ *
+ * @param {*} pullRequestCount
+ * @param {*} otherReposCount
+ * @returns
```
Comment (kabirbaidhya) [inline src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js]:
```suggestion
 * @returns {string}
```

File: src/utils/isPRLabelValid.js [hunk 6]
```diff
@@ -0,0 +1,19 @@
...
+
+// Makes The Array case insensitive for checking
+const labelIgnoreRegex = new RegExp(FROGTOBERFEST_IGNORE_LABEL_LIST.join('|'), 'i');
+
+/**
+ * Checks whether Pull request is valid against Frogtoberfest label list.
+ *
+ * @param {*} labels
+ */
+export default function isPRLabelValid(labels) {
```
Comment (kabirbaidhya) [inline src/utils/isPRLabelValid.js]: Don't need to have one function in one file. You can create a util file like `utils/pullRequest.js` and put all the functions related to PRs in that. Also you can do named export instead of default export here.

Comment (mesaugat) [inline src/utils/isPRLabelValid.js]: This is already done by @vhndaree in #16. However we can take some cues from here to improve his approach.

File: src/utils/isPRLabelValid.js [hunk 7]
```diff
@@ -0,0 +1,19 @@
...
+  const result = labels.map(label => {
+    // returns false if label has name in frogtoberfest label list
+    return !labelIgnoreRegex.test(label.name);
```
Comment (kabirbaidhya) [inline src/utils/isPRLabelValid.js]: This could be a simple string comparison like: `label.name.toLowerCase() === value` no need regex here - which could be pretty much expensive than string compare.

File: src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js [hunk 8]
```diff
@@ -0,0 +1,44 @@
...
+  const isShowingOff = pullRequestCount > pullRequestAmount && otherReposCount > otherReposAmount;
+
+  if (isShowingOff) {
+    return messages[messages.length - 1];
+  }
+
+  return messages[pullRequestCount];
+};
+
+export default getMessage;
```
Comment (kabirbaidhya) [inline src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js]: No need single util function per file. You can create a common util file and export all these utility functions. See my comments above related to this.

File: src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js (hunk 2 above)
Comment (kabirbaidhya) [reply src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js]: No need to repeat the same messages. May be you can change rephrase some of the sentences if that is what you need.

**Comment by kabirbaidhya** [comment]
@bhattaraib58 Can you pull the latest master from the upstream and resolve conflicts. The master has some of the changes you need in your branch too.

File: src/pages/User/components/PullRequests/UserInfo/index.js [hunk 9]
```diff
@@ -4,23 +4,33 @@ import UserImage from './UserImage';
...
-      <PullRequestCount pullRequestCount={pullRequestCount} pullRequestAmount={pullRequestAmount} />
-      <ResultMessage message="Total PR'S" />
-    </div>
-    <div
-      className="flex flex-wrap justify-center content-center flex-col"
-      style={otherReposCount >= otherReposAmount ? completeMark : incompleteMark}
-    >
-      <PullRequestCount pullRequestCount={otherReposCount} pullRequestAmount={otherReposAmount} />
-      <ResultMessage message="Other Repo PR'S" />
+
```
Comment (nishanbajracharya) [inline src/pages/User/components/PullRequests/UserInfo/index.js]: Remove the whitespace here

File: src/pages/User/components/PullRequests/index.js [hunk 10]
```diff
@@ -88,6 +90,8 @@ class PullRequests extends Component {
       );
 
       const [data, userDetail] = await Promise.all(allResponses);
+
+      data.items = data.items.filter(pullRequest => isPRLabelValid(pullRequest.labels));
```
Comment (nishanbajracharya) [inline src/pages/User/components/PullRequests/index.js]: Let's try and avoid mutations like this. Instead `setState` the filtered array in line `98`.

File: src/utils/isPRLabelValid.js [hunk 11]
```diff
@@ -0,0 +1,19 @@
+// Ignore list of labels for frogtoberfest, add at end of array for more list
+const FROGTOBERFEST_IGNORE_LABEL_LIST = ['invalid'];
+
+// Makes The Array case insensitive for checking
+const labelIgnoreRegex = new RegExp(FROGTOBERFEST_IGNORE_LABEL_LIST.join('|'), 'i');
```
Comment (nishanbajracharya) [inline src/utils/isPRLabelValid.js]: Regex to check for invalid label is probably not a good idea. A simple string comparison should be enough.

**Comment by nishanbajracharya** [comment]
@bhattaraib58 I think the issue referenced in #15 hasn't been resolved by this PR. If I'm not mistaken, this PR adds a new message below the PR count, instead of replacing the text above the user name input field signifying the `no. of days remaining to complete the challenge`. The `days remaining` message should either be replaced or removed if the challenge is completed.

File: src/pages/User/components/PullRequests/UserInfo/Message/Message.js [hunk 12]
```diff
@@ -0,0 +1,14 @@
+import React from 'react';
+import PropTypes from 'prop-types';
+import getMessage from './getMessage';
+
+const Message = ({ pullRequestCount, otherReposCount }) => (
+  <h2 className="font-medium text-red-dark text-3xl">{getMessage(pullRequestCount, otherReposCount)}</h2>
```
Comment (nishanbajracharya) [inline src/pages/User/components/PullRequests/UserInfo/Message/Message.js]: The text should not be `dark red` which would signify a failure action. Instead either something more neutral like `blue/black/dark-grey` or success like `green`.

File: src/pages/User/components/PullRequests/UserInfo/Message/Message.js [hunk 13]
```diff
@@ -0,0 +1,14 @@
+import React from 'react';
+import PropTypes from 'prop-types';
+import getMessage from './getMessage';
+
+const Message = ({ pullRequestCount, otherReposCount }) => (
+  <h2 className="font-medium text-green-darker text-3xl m-3">{getMessage(pullRequestCount, otherReposCount)}</h2>
```
Comment (mesaugat) [inline src/pages/User/components/PullRequests/UserInfo/Message/Message.js]: IMO, `<h2>` is too big. We can use a simple `<p>` tag?

File: src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js [hunk 14]
```diff
@@ -0,0 +1,44 @@
+import { pullRequestAmount, otherReposAmount } from '../../pullRequestAmount';
+
+const messages = [
+  "It's not too late to start!",
+  'Off to a great start, keep going!',
+  'Keep going!',
+  'Keep it up!',
+  'Nice work, Keep it up !',
```
Comment (mesaugat) [inline src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js]:
```suggestion
  'Nice work, keep it up!',
```

File: src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js [hunk 15]
```diff
@@ -0,0 +1,44 @@
...
+  "Nice! Now, don't stop!",
```
Comment (mesaugat) [inline src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js]:
```suggestion
  "Now, don't stop!",
```

File: src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js [hunk 16]
```diff
@@ -0,0 +1,44 @@
...
+  "Keep Going, don't stop!",
+  'So close!',
+  'So close! Keep it up !',
```
Comment (mesaugat) [inline src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js]:
```suggestion
  'Inching close!',
```

File: src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js [hunk 17]
```diff
@@ -0,0 +1,44 @@
+import { pullRequestAmount, otherReposAmount } from '../../pullRequestAmount';
+
+const messages = [
+  "It's not too late to start!",
+  'Off to a great start, keep going!',
+  'Keep going!',
+  'Keep it up!',
+  'Nice work, Keep it up !',
+  "Nice! Now, don't stop!",
+  "Keep Going, don't stop!",
```
Comment (mesaugat) [inline src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js]:
```suggestion
  "Can't stop now",
```

File: src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js [hunk 18]
```diff
@@ -0,0 +1,44 @@
...
+  }
+
+  if (currentMonth > 9) {
+    return "This year's result.";
+  }
+
+  const isShowingOff = pullRequestCount > pullRequestAmount && otherReposCount > otherReposAmount;
+
+  if (isShowingOff) {
+    return messages[messages.length - 1];
```
Comment (mesaugat) [inline src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js]: return the text directly here.

```js
return "Now you're just showing off!";
```

File: src/pages/User/components/PullRequests/UserInfo/index.js [hunk 19]
```diff
@@ -4,23 +4,33 @@ import UserImage from './UserImage';
...
+        </div>
+        <div
+          className="flex flex-wrap justify-center content-center flex-col"
+          style={otherReposCount >= otherReposAmount ? completeMark : incompleteMark}
+        >
+          <PullRequestCount pullRequestCount={otherReposCount} pullRequestAmount={otherReposAmount} />
+          <ResultMessage message="Other Repo PR'S" />
+        </div>
+      </div>
+
```
Comment (mesaugat) [inline src/pages/User/components/PullRequests/UserInfo/index.js]: Remove whitespace.

File: src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js [hunk 20]
```diff
@@ -0,0 +1,44 @@
...
+  "Nice! Now, don't stop!",
+  "Keep Going, don't stop!",
+  'So close!',
+  'So close! Keep it up !',
+  'Way to go!',
+  "Now you're just showing off!"
+];
+
+/**
+ * Get Messages Based on Pull Request and Other Repo count.
```
Comment (mesaugat) [inline src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js]: Get motivational message based on pull requests count.

**Comment by kabirbaidhya** [comment]
Pull the latest master and resolve the above comments - then we can proceed.

**Comment by bhattaraib58** [comment]
> @bhattaraib58 I think the issue #15 hasn't been resolved by this PR. If I'm not mistaken, this PR adds a new message below the PR count, instead of replacing the text above the user name input field signifying the `no. of days remaining to complete the challenge`. The `days remaining` message should either be **replaced** or **removed** if the challenge is completed.

Done dai, please check updated screenshot above.

File: src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js (hunk 18 above)
Comment (bhattaraib58) [reply src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js]: will it be good to write the string as proposed directly, if change is needed we would have to change at two places.

Comment (kabirbaidhya) [reply src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js]: Makes sense.

File: src/components/UsernameForm/index.js [hunk 21]
```diff
@@ -63,21 +70,42 @@ class UsernameForm extends Component {
...
-      </form>
-    </div>
-  );
+  /**
+   * Check the condition for eligibility.
+   *
+   * @param {*} pullRequestCount
+   * @param {*} otherReposCount
+   * @returns {boolean}
+   * @memberof UsernameForm
```
Comment (kabirbaidhya) [inline src/components/UsernameForm/index.js]: Remove this.

File: src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js [hunk 22]
```diff
@@ -0,0 +1,44 @@
+import { TOTAL_PR_COUNT, TOTAL_OTHER_PR_COUNT } from '../../../../../../config';
+
+const messages = [
+  "It's not too late to start!",
+  'Off to a great start, keep going!',
+  'Keep going!',
+  'Keep it up!',
+  'Nice work!',
+  "Now, don't stop!",
```
Comment (kabirbaidhya) [inline src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js]: Half way there, don't stop now!

File: src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js [hunk 23]
```diff
@@ -0,0 +1,44 @@
...
+  "Can't stop now",
```
Comment (kabirbaidhya) [inline src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js]: Going great, just few more to go!

File: src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js [hunk 24]
```diff
@@ -0,0 +1,44 @@
...
+  'So close!',
+  'Nearing completion, go go go!',
```
Comment (kabirbaidhya) [inline src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js]: Almost there, go go go!

File: src/pages/User/index.js [hunk 25]
```diff
@@ -1,24 +1,94 @@
...
+        otherReposCount
+      });
+    }
+  }
+
+  /**
+   * Render.
+   *
+   * @returns
+   * @memberof User
```
Comment (kabirbaidhya) [inline src/pages/User/index.js]: Remote.

File: src/pages/User/index.js [hunk 26]
```diff
@@ -1,24 +1,94 @@
...
+
+    this.setUserContributionCount = this.setUserContributionCount.bind(this);
+  }
+
+  /**
+   * Set User Contribution Count of Pull requests and other repo pull request count.
+   *
+   * @param {*} pullRequestCount
+   * @param {*} otherReposCount
+   * @memberof User
```
Comment (kabirbaidhya) [inline src/pages/User/index.js]: .

File: src/pages/User/index.js [hunk 27]
```diff
@@ -1,24 +1,94 @@
...
+ * @export
+ * @class User
+ * @extends {Component}
+ */
+export class User extends Component {
+  /**
+   * Creates an instance of User.
+   *
+   * @param {*} props
+   * @memberof User
```
Comment (kabirbaidhya) [inline src/pages/User/index.js]: .

File: src/pages/User/index.js [hunk 28]
```diff
@@ -1,24 +1,94 @@
...
+// );
+
+// import React, {  } from 'react';
+
+/**
+ * User Component
+ *
+ * @export
+ * @class User
+ * @extends {Component}
```
Comment (kabirbaidhya) [inline src/pages/User/index.js]: Remote all these - don't need them.

File: src/pages/User/index.js [hunk 29]
```diff
@@ -1,24 +1,94 @@
...
+//     <SiteTitle>Frogtoberfest Checker</SiteTitle>
+//     <UsernameForm username={username} />
+//     <PullRequests username={username} />
+//   </Fragment>
+// );
+
+// import React, {  } from 'react';
+
+/**
+ * User Component
```
Comment (kabirbaidhya) [inline src/pages/User/index.js]: full stop at the end.

File: src/pages/User/index.js [hunk 30]
```diff
@@ -1,24 +1,94 @@
...
+//     <Helmet>
+//       <title>{username}</title>
+//     </Helmet>
+//     <SiteTitle>Frogtoberfest Checker</SiteTitle>
+//     <UsernameForm username={username} />
+//     <PullRequests username={username} />
+//   </Fragment>
+// );
+
+// import React, {  } from 'react';
```
Comment (kabirbaidhya) [inline src/pages/User/index.js]: Remove commented code if they're of no use.

**Comment by kabirbaidhya** [comment]
@bhattaraib58 Great. Thanks for the hard work!

This mostly looks good - I've commented few more stuff from my end. 

@mesaugat @nishanbajracharya Please review.

File: src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js (hunk 24 above)
Comment (bhattaraib58) [reply src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js]: Added.

File: src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js (hunk 23 above)
Comment (bhattaraib58) [reply src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js]: Added dai.

File: src/components/UsernameForm/index.js [hunk 31]
```diff
@@ -63,21 +70,41 @@ class UsernameForm extends Component {
...
-    </div>
-  );
+  /**
+   * Check the condition for eligibility.
+   *
+   * @param {*} pullRequestCount
+   * @param {*} otherReposCount
+   * @returns {boolean}
+   */
+  conditionChecker(pullRequestCount, otherReposCount) {
```
Comment (kabirbaidhya) [inline src/components/UsernameForm/index.js]: Functions are actions so they're usually named prefixed with a "verb" to describe what they do. Better name for this one could be - `checkEligibility`.

Comment (bhattaraib58) [reply src/components/UsernameForm/index.js]: Thank u dai.

File: src/components/UsernameForm/CompletionMessage.js [hunk 32]
```diff
@@ -0,0 +1,16 @@
...
+const CompletionMessage = () => {
+  return (
+    <div className="text-center text-white pb-2" style={completionMessageStyle}>
+      <p className="text-2xl">Thank you for your contributions!</p>
+      <p className="text-xl">You have sucessfully completed Frogtoberfest 2019</p>
+    </div>
+  );
+};
+
+const completionMessageStyle = {
```
Comment (mesaugat) [inline src/components/UsernameForm/CompletionMessage.js]: You can use `text-green` class instead of this here. Avoid `inline` styling as much as possible. We can use tailwind css utility classes.

File: src/components/UsernameForm/CompletionMessage.js [hunk 33]
```diff
@@ -0,0 +1,16 @@
+import React from 'react';
+
+const CompletionMessage = () => {
+  return (
+    <div className="text-center text-white pb-2" style={completionMessageStyle}>
+      <p className="text-2xl">Thank you for your contributions!</p>
```
Comment (mesaugat) [inline src/components/UsernameForm/CompletionMessage.js]: Full stop here.

File: src/components/UsernameForm/CompletionMessage.js (hunk 32 above)
Comment (mesaugat) [reply src/components/UsernameForm/CompletionMessage.js]: Also,

```diff
- sucessfully
+ successfully
```

Comment (mesaugat) [reply src/components/UsernameForm/CompletionMessage.js]: Add a `!` at the end.

File: src/components/UsernameForm/CompletionMessage.js [hunk 34]
```diff
@@ -0,0 +1,16 @@
+import React from 'react';
+
+const CompletionMessage = () => {
+  return (
+    <div className="text-center text-white pb-2" style={completionMessageStyle}>
```
Comment (mesaugat) [inline src/components/UsernameForm/CompletionMessage.js]: `text-white` ?

Use `text-green`?

File: src/components/UsernameForm/index.js [hunk 35]
```diff
@@ -63,21 +70,41 @@ class UsernameForm extends Component {
...
-    </div>
-  );
+  /**
+   * Check the condition for eligibility.
+   *
+   * @param {*} pullRequestCount
+   * @param {*} otherReposCount
+   * @returns {boolean}
+   */
+  checkEligibility(pullRequestCount, otherReposCount) {
```
Comment (mesaugat) [inline src/components/UsernameForm/index.js]: Can we rename these arguments?

```diff
- pullRequestCount
+ totalPrCount
```

```diff
- otherReposCount
+ totalOtherPrCount
```

File: src/components/UsernameForm/index.js [hunk 36]
```diff
@@ -63,21 +70,41 @@ class UsernameForm extends Component {
...
+
+    return otherReposCount >= TOTAL_OTHER_PR_COUNT;
+  }
+
+  render = () => {
+    const isComplete = this.checkEligibility(this.props.pullRequestCount, this.props.otherReposCount);
+
+    return (
+      <div className="pb-8 md:pt-16">
+        {isComplete ? <CompletionMessage /> : <TimeMessage />}
```
Comment (mesaugat) [inline src/components/UsernameForm/index.js]: Rename component `<TimeMessage />` to `<MotivationalMessage />`.

File: src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js [hunk 37]
```diff
@@ -0,0 +1,44 @@
+import { TOTAL_PR_COUNT, TOTAL_OTHER_PR_COUNT } from '../../../../../../config';
+
+const messages = [
+  "It's not too late to start!",
+  'Off to a great start, keep going!',
+  'Keep going!',
+  'Keep it up!',
+  "Half way there, don't stop now!",
+  "Now, don't stop!",
```
Comment (mesaugat) [inline src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js]: Remove this message as it is similar to the one above.

In place of `Now, don't stop!` use `You are right on track!`

File: src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js [hunk 38]
```diff
@@ -0,0 +1,44 @@
...
+  "Can't stop now",
```
Comment (mesaugat) [inline src/pages/User/components/PullRequests/UserInfo/Message/getMessage.js]: Add a `!` in the end.

File: src/pages/User/components/PullRequests/UserInfo/Message/index.js [hunk 39]
```diff
@@ -0,0 +1,14 @@
+import React from 'react';
+import PropTypes from 'prop-types';
+import getMessage from './getMessage';
+
+const Message = ({ pullRequestCount, otherReposCount }) => (
```
Comment (mesaugat) [inline src/pages/User/components/PullRequests/UserInfo/Message/index.js]: Rename to `MotivationalMessage`

Comment (mesaugat) [reply src/pages/User/components/PullRequests/UserInfo/Message/index.js]: Rename the file too.

`Message` is too generic and if should be able to be used everywhere which is not the case here.

File: src/pages/User/index.js [hunk 40]
```diff
@@ -1,24 +1,77 @@
...
+        pullRequestCount,
+        otherReposCount
+      });
+    }
+  }
+
+  /**
+   * Render.
+   *
+   * @returns
```
Comment (mesaugat) [inline src/pages/User/index.js]: Empty `@returns`?

File: src/pages/User/index.js [hunk 41]
```diff
@@ -1,24 +1,77 @@
...
-    params: { username }
+/**
+ * User Component.
+ *
+ * @class User
+ * @extends {Component}
+ */
+export class User extends Component {
+  /**
+   * Creates an instance of User.
```
Comment (mesaugat) [inline src/pages/User/index.js]: Creates an instance of User? I think this is not correct.

File: src/pages/User/index.js [hunk 42]
```diff
@@ -1,24 +1,77 @@
...
+    this.setUserContributionCount = this.setUserContributionCount.bind(this);
+  }
+
+  /**
+   * Set User Contribution Count of Pull requests and other repo pull request count.
+   *
+   * @param {*} pullRequestCount
+   * @param {*} otherReposCount
+   */
+  setUserContributionCount(pullRequestCount, otherReposCount) {
```
Comment (mesaugat) [inline src/pages/User/index.js]: Rename the arguments as I stated above.

**Comment by mesaugat** [comment]
@bhattaraib58 There are few changes that I've requested. 😉 

Thank you for contributing.

File: src/pages/User/components/PullRequests/index.js [hunk 43]
```diff
@@ -86,11 +87,13 @@ class PullRequests extends Component {
             })
           )
       );
-      
+
       const [responseData, userDetail] = await Promise.all(allResponses);
       const data = this.getValidPullRequests(responseData);
       const count = this.counterOtherRepos(data, userDetail);
```
Comment (mesaugat) [inline src/pages/User/components/PullRequests/index.js]: Should be `this.countOtherRepos`. Anyways, we can do this later.

**Comment by bhattaraib58** [comment]
> @bhattaraib58 Can you add the latest screenshot in the description before we merge this?

Done Dai.
