### PR TITLE
Limit GitHub users to Leapfrog Technology GitHub Organization

### LINKED ISSUE #21: Limit GitHub users to Leapfrog Technology GitHub Organization
**Current behavior:**
Anyone can put in their GitHub username and check their progress regardless of whether they are associated to Leapfrog or not.

**Expected behavior:**
Limit the search to only members in https://github.com/leapfrogtechnology

If anyone outside of leapfrogtechnology decides to check their progress, show an "Aw snap! You are not a member of Leapfrog Technology and link back to our career page ;-)"

**Steps to reproduce:**
Just put in a username not associated with Leapfrog Technology.

### PR DESCRIPTION
**Pull request by Vhndaree**
## Issue
Previously, any valid user of github with github id is able to check their frogtoberfest challenge acomplishments, which doesn't make any sense of Name **Frogtoberfest**. 

Resolves #21 

## Usage Changes
This change add new api to fetch response if user is a member of leapfrog technology, redirects person who enters any non leapfrog github member to LF career page and only display fest accomplishment if user is a LFtechnology github member.

## Screenshot
**Before fix(currently on Prod)**
Screenshot from 2019-10-23 20-57-37

**After fix**
Screenshot from 2019-10-24 00-41-03

### CODE REVIEW

File: src/pages/User/components/PullRequests/index.js [hunk 1]
```diff
@@ -87,9 +88,14 @@ class PullRequests extends Component {
           )
       );
 
-      const [data, userDetail] = await Promise.all(allResponses);
+      const [data, userDetail, lFMembershipStatus] = await Promise.all(allResponses);
       const count = this.counterOtherRepos(data, userDetail);
 
+      // if user is a member of Leapfrog then there will no any response
+      if (lFMembershipStatus !== undefined) {
+        alert('Aw snap! You are not a member of Leapfrog Technology!');
```
Comment (kabirbaidhya) [inline src/pages/User/components/PullRequests/index.js]: Showing a classic `alert` is not the a neat solution; neither it is good from UX perspective. You can create a component to show this in the UI as a message along with the link below.

File: src/pages/User/components/PullRequests/index.js [hunk 2]
```diff
@@ -87,9 +88,14 @@ class PullRequests extends Component {
           )
       );
 
-      const [data, userDetail] = await Promise.all(allResponses);
+      const [data, userDetail, lFMembershipStatus] = await Promise.all(allResponses);
```
Comment (kabirbaidhya) [inline src/pages/User/components/PullRequests/index.js]: This same function right now does a lot of things. Can you extract this logic to a separate function responsible for fetching user's information only? Something like this. 

```js
const userInfo = await fetchUserInfo(username); // This should do everything under the hood and return a single object. 

... 

async function fetchUserInfo(username) {
  ...  
  const [data, detail, membershipStatus] = await Promise.all(...);
  const isOrgMember = !!membershipStatus;

  return { data, detail, isOrgMember };
} 
```

File: src/pages/User/components/PullRequests/index.js [hunk 3]
```diff
@@ -8,6 +8,39 @@ import PullRequest from './PullRequest';
...
 import MeLinkInfo from './MeLinkInfo';
 import { GITHUB_TOKEN } from '../../../../config';
+import NotAMember from '../Modal/NotAMember';
+
+const GITHUB_ORG_NAME = 'leapfrogtechnology';
+
+/**
+ * returns an object containing user info
+ *
+ * @param {String} username
```
Comment (kabirbaidhya) [inline src/pages/User/components/PullRequests/index.js]:
```suggestion
 * @param {string} username
```

File: src/pages/User/components/PullRequests/index.js [hunk 4]
```diff
@@ -8,6 +8,39 @@ import PullRequest from './PullRequest';
...
+ */
+export async function fetchUserInfo(username) {
+  const apiUrl = [
+    `https://api.github.com/search/issues?q=author:${username}+is:pr+created:2019-10-01..2019-10-31`,
+    `https://api.github.com/search/users?q=user:${username}`,
+    `https://api.github.com/orgs/${GITHUB_ORG_NAME}/members/${username}`
+  ];
+
+  const allResponses = apiUrl.map(url =>
+    fetch(url, {
```
Comment (kabirbaidhya) [inline src/pages/User/components/PullRequests/index.js]: Extract this as a separate function `fetchInfoFromGitHub(url, token)`. It could be as simple as this:
```js
const result = apiUrls.map(url => fetchInfoFromGitHub(url, GITHUB_TOKEN))
```

File: src/pages/User/components/PullRequests/index.js [hunk 5]
```diff
@@ -8,6 +8,39 @@ import PullRequest from './PullRequest';
...
+const GITHUB_ORG_NAME = 'leapfrogtechnology';
+
+/**
+ * returns an object containing user info
+ *
+ * @param {string} username
+ * @returns {*}
+ */
+export async function fetchUserInfo(username) {
+  const apiUrl = [
```
Comment (kabirbaidhya) [inline src/pages/User/components/PullRequests/index.js]: It's a list of urls (plural) - the name should reflect that too. 
```suggestion
  const apiUrls = [
```

File: src/pages/User/components/PullRequests/index.js [hunk 6]
```diff
@@ -8,6 +8,39 @@ import PullRequest from './PullRequest';
...
+    `https://api.github.com/orgs/${GITHUB_ORG_NAME}/members/${username}`
+  ];
+
+  const allResponses = apiUrl.map(url =>
+    fetch(url, {
+      headers: {
+        Authorization: `token ${GITHUB_TOKEN}`
+      }
+    })
+      .then(response => response)
```
Comment (kabirbaidhya) [inline src/pages/User/components/PullRequests/index.js]: If transform it to json here, you won't need to do it later. 
```suggestion
      .then(response => response.json())
```

File: src/pages/User/components/PullRequests/index.js [hunk 7]
```diff
@@ -63,40 +96,25 @@ class PullRequests extends Component {
...
 
-      this.setState({
-        data: this.getValidPullRequests(data),
-        userDetail,
-        loading: false,
-        otherReposCount: count,
-        error: null
-      });
+      if (!isOrgMember) {
+        this.setState({
```
Comment (kabirbaidhya) [inline src/pages/User/components/PullRequests/index.js]: Extract these to separate methods with names reflecting what they'd do eg: `showNotAMemberModal`.

File: src/pages/User/components/PullRequests/index.js [hunk 8]
```diff
@@ -63,40 +96,25 @@ class PullRequests extends Component {
...
+          openModal: true,
+          loading: false,
+          data: null,
+          userDetail: null
+        });
+      } else {
+        this.setState({
```
Comment (kabirbaidhya) [inline src/pages/User/components/PullRequests/index.js]: Same here - new method `displayPullRequests`

**Comment by kabirbaidhya** [comment]
@Vhndaree There's a build failing. Please check the Travis CI log and resolve the issue as well.

File: src/pages/User/components/Modal/NotAMember.js [hunk 9]
```diff
@@ -0,0 +1,32 @@
...
+          transform: 'translateY(0vh)',
+          opacity: '1'
+        }}
+      >
+        <div className="modal-header">
+          <h3>Aw snap!</h3>
+        </div>
+        <div className="modal-body">
+          <p>You are not a member of Leapfrog Technology.</p>
+          <p>You can be a member <a href="https://www.lftechnology.com/careers/">here.</a></p>
```
Comment (kabirbaidhya) [inline src/pages/User/components/Modal/NotAMember.js]:
```suggestion
          <p>You can join us from <a href="https://www.lftechnology.com/careers/">here</a> :).</p>
```

File: src/utils/fetchInfoFromGitHub.js [hunk 10]
```diff
@@ -0,0 +1,13 @@
+const fetchInfoFromGitHub = (url, GITHUB_TOKEN) => {
```
Comment (kabirbaidhya) [inline src/utils/fetchInfoFromGitHub.js]: Don't create a new util file for each function you write. Add this function in an existing utility file under `utils/`. Also define functions using the `function` keyworld and you can define it as:
```js
export function fetchInfoFromGitHub(url, githubToken) {
  ...
}
```

File: src/utils/fetchInfoFromGitHub.js [hunk 11]
```diff
@@ -0,0 +1,13 @@
...
+  const response = fetch(url, {
```
Comment (kabirbaidhya) [inline src/utils/fetchInfoFromGitHub.js]: return directly

File: src/pages/User/components/PullRequests/index.js [hunk 12]
```diff
@@ -111,6 +98,10 @@ class PullRequests extends Component {
     }
   };
 
+  /**
+   * Displays error message.
+   */
+
```
Comment (kabirbaidhya) [inline src/pages/User/components/PullRequests/index.js]: Remove unnecessary blank line.

File: src/pages/User/components/Modal/NotAMember.js [hunk 13]
```diff
@@ -0,0 +1,39 @@
...
+          opacity: '1'
+        }}
+      >
+        <div className="modal-header">
+          <h3>Aw snap!</h3>
+        </div>
+        <div className="modal-body">
+          <p>You are not a member of Leapfrog Technology.</p>
+          <p>
+            You can join us from <a href="https://www.lftechnology.com/careers/"> here </a> :).
```
Comment (kabirbaidhya) [inline src/pages/User/components/Modal/NotAMember.js]: This url can go to the `config.js` file too. 
```js
export const CAREERS_PAGE_URL = 'https://www.lftechnology.com/careers';
```

File: src/utils/fetchInfoFromGitHub.js (hunk 10 above)
Comment (kabirbaidhya) [reply src/utils/fetchInfoFromGitHub.js]: Also don't forget to add jsdocs once you rewrite it as a `function`.

File: src/pages/User/components/Modal/NotAMember.css [hunk 14]
```diff
@@ -0,0 +1,48 @@
+.modal-wrapper {
+	background: white;
```
Comment (sbimochan) [inline src/pages/User/components/Modal/NotAMember.css]: Are we really using 8 spaces for css? Can you check other css files? It must be two.

File: src/pages/User/components/Modal/NotAMember.js [hunk 15]
```diff
@@ -0,0 +1,39 @@
+import React from 'react';
+import PropTypes from 'prop-types';
+
+import './NotAMember.css';
```
Comment (sbimochan) [inline src/pages/User/components/Modal/NotAMember.js]: CSS filenames should be all lowercased.

File: src/pages/User/components/Modal/NotAMember.js [hunk 16]
```diff
@@ -0,0 +1,39 @@
...
+
+const NotAMember = ({ close }) => {
+  return (
+    <div>
+      <div
+        className="modal-wrapper"
+        style={{
```
Comment (sbimochan) [inline src/pages/User/components/Modal/NotAMember.js]: This can go to a css file since you have a class name.

File: src/pages/User/components/Modal/NotAMember.js [hunk 17]
```diff
@@ -0,0 +1,39 @@
...
+          transform: 'translateY(0vh)',
+          opacity: '1'
+        }}
+      >
+        <div className="modal-header">
+          <h3>Aw snap!</h3>
```
Comment (sbimochan) [inline src/pages/User/components/Modal/NotAMember.js]: Can we use more ‘w’ here? Like Awww ? 😂

File: src/pages/User/components/PullRequests/index.js [hunk 18]
```diff
@@ -1,14 +1,35 @@
...
 import ErrorText from './ErrorText';
 import UserInfo from './UserInfo';
+import fetchInfoFromGitHub from '../../../../utils/fetchInfoFromGitHub';
+import { GITHUB_TOKEN, TOTAL_PR_COUNT, TOTAL_OTHER_PR_COUNT, GITHUB_ORG_NAME } from '../../../../config';
+
+/**
+ * Returns an object containing user info.
+ *
+ * @param {string} username
+ * @returns {*}
```
Comment (sbimochan) [inline src/pages/User/components/PullRequests/index.js]: Please add in @returns too.

File: src/pages/User/components/PullRequests/index.js [hunk 19]
```diff
@@ -1,14 +1,35 @@
...
-import { GITHUB_TOKEN, TOTAL_PR_COUNT, TOTAL_OTHER_PR_COUNT } from '../../../../config';
 import ShareButtons from './ShareButtons';
 import LoadingIcon from './LoadingIcon';
 import PullRequest from './PullRequest';
 import IssuesLink from './IssuesLink';
 import MeLinkInfo from './MeLinkInfo';
+import NotAMember from '../Modal/NotAMember';
 import ErrorText from './ErrorText';
 import UserInfo from './UserInfo';
+import fetchInfoFromGitHub from '../../../../utils/fetchInfoFromGitHub';
```
Comment (sbimochan) [inline src/pages/User/components/PullRequests/index.js]: This could have been shortened out to ‘utils/....’ by using NODE_PATH=src in .env file. Optional.

File: src/pages/User/components/PullRequests/index.js [hunk 20]
```diff
@@ -165,6 +156,22 @@ class PullRequests extends Component {
     return count;
   }
 
+  /**
+   * @param {*} userInfo
```
Comment (sbimochan) [inline src/pages/User/components/PullRequests/index.js]: Is it really * ?

File: src/utils/Utils.js [hunk 21]
```diff
@@ -0,0 +1,25 @@
+/**
+ * Utility functions.
+ */
+const Utils = {
+  // Returns formatted date, eg Wed Jul 28 1993.
+  dateFormatter(dateTime) {
```
Comment (kabirbaidhya) [inline src/utils/Utils.js]: export function formatDate()

File: src/utils/Utils.js [hunk 22]
```diff
@@ -0,0 +1,25 @@
...
+    const date = new Date(dateTime);
+
+    return date.toDateString();
+  },
+  //Fetches from github apis.
+  fetchInfoFromGitHub(url, GITHUB_TOKEN) {
```
Comment (kabirbaidhya) [inline src/utils/Utils.js]: export function fetchInfoFromGitHub

File: src/utils/Utils.js [hunk 23]
```diff
@@ -0,0 +1,25 @@
+/**
+ * Utility functions.
+ */
+const Utils = {
```
Comment (kabirbaidhya) [inline src/utils/Utils.js]: Remove this const declaration.

File: src/pages/User/components/PullRequests/PullRequest/PullRequestInfo.js [hunk 24]
```diff
@@ -1,6 +1,6 @@
 import React from 'react';
 import PropTypes from 'prop-types';
-import dateFormatter from '../../../../../utils/dateFormater';
+import Utils from '../../../../../utils/Utils';
```
Comment (kabirbaidhya) [inline src/pages/User/components/PullRequests/PullRequest/PullRequestInfo.js]:
```
import { formatDate } from '../../utils.js';
```

File: src/config.js [hunk 25]
```diff
@@ -2,3 +2,7 @@ export const GITHUB_TOKEN = process.env.REACT_APP_GITHUB_TOKEN;
 export const HOSTNAME = process.env.REACT_APP_HOSTNAME;
 export const TOTAL_PR_COUNT = 10;
 export const TOTAL_OTHER_PR_COUNT = 4;
+export const ORG_INFO = {
+  GITHUB_ORG_NAME: 'leapfrogtechnology',
```
Comment (kabirbaidhya) [inline src/config.js]: Define individual constants.

Comment (kabirbaidhya) [inline src/config.js]:
```suggestion
export const GITHUB_ORG_NAME = 'leapfrogtechnology';
```

File: src/config.js [hunk 26]
```diff
@@ -2,3 +2,7 @@ export const GITHUB_TOKEN = process.env.REACT_APP_GITHUB_TOKEN;
...
+  ORG_REDIRECT_URL: 'https://www.lftechnology.com/careers/'
```
Comment (kabirbaidhya) [inline src/config.js]:
```suggestion
export const ORG_REDIRECT_URL = 'https://www.lftechnology.com/careers';
```

File: src/pages/User/components/PullRequests/PullRequest/PullRequestInfo.js [hunk 27]
```diff
@@ -14,7 +14,7 @@ const PullRequestInfo = ({ pullRequest }) => (
       </a>
     </div>
     <div className="text-grey-dark">
-      {pullRequest.title} on {dateFormatter(pullRequest.created_at)}
+      {pullRequest.title} on {Utils.dateFormatter(pullRequest.created_at)}
```
Comment (kabirbaidhya) [inline src/pages/User/components/PullRequests/PullRequest/PullRequestInfo.js]: .

File: src/pages/User/components/PullRequests/ErrorText.js [hunk 28]
```diff
@@ -1,14 +1,14 @@
 import React from 'react';
 import PropTypes from 'prop-types';
 
-const ErrorText = ({ errorMessage }) => (
+const ErrorText = ({ errorMessage, notAUserErrorMsg }) => (
```
Comment (sbimochan) [inline src/pages/User/components/PullRequests/ErrorText.js]: notAUserErrorMsg is not needed here because you're sending error messages in errorMessage.

File: src/utils/utils.js [hunk 29]
```diff
@@ -0,0 +1,30 @@
+/**
+ * Returns formatted date eg Wed Jul 28 1993.
+ *
+ * @param {date} dateTime
+ * @returns {date}
```
Comment (kabirbaidhya) [inline src/utils/utils.js]: string

File: src/utils/utils.js [hunk 30]
```diff
@@ -0,0 +1,30 @@
+/**
+ * Returns formatted date eg Wed Jul 28 1993.
+ *
+ * @param {date} dateTime
```
Comment (kabirbaidhya) [inline src/utils/utils.js]:
```suggestion
 * @param {Date} dateTime
```

File: src/utils/utils.js [hunk 31]
```diff
@@ -0,0 +1,30 @@
...
+ * @returns {date}
+ */
+export function dateFormatter(dateTime) {
```
Comment (kabirbaidhya) [inline src/utils/utils.js]: Rename this to `formatDate`

File: src/utils/utils.js [hunk 32]
```diff
@@ -0,0 +1,30 @@
...
+}
+
+/**
+ * Fetch and return responses from Github apis.
+ *
+ * @param {*} url
+ * @param {*} GITHUB_TOKEN
+ * @returns {Promise}
+ */
+export function fetchInfoFromGitHub(url, GITHUB_TOKEN) {
```
Comment (kabirbaidhya) [inline src/utils/utils.js]: variables must be in camelCase.
```suggestion
export function fetchInfoFromGitHub(url, githubToken) {
```

File: src/utils/utils.js [hunk 33]
```diff
@@ -0,0 +1,30 @@
...
+  const date = new Date(dateTime);
+
+  return date.toDateString();
+}
+
+/**
+ * Fetch and return responses from Github apis.
+ *
+ * @param {*} url
+ * @param {*} GITHUB_TOKEN
```
Comment (kabirbaidhya) [inline src/utils/utils.js]: .

**Comment by kabirbaidhya** [comment]
Awesome. Kada :100: . Thanks for the hard work :+1:
